-- NOTE: These are Lua patterns, not globs. '.' is a wildcard in Lua — use '%.' for a
-- literal dot. e.g. '.git' would match any path containing '-git', 'agit', etc.
-- which caused files like 'reinstall-gitsy' to be hidden from Telescope find_files.
--
-- Likewise, a bare directory name is matched as a substring ANYWHERE in the path,
-- so 'war' hid src/middleware/* (middle-WAR-e) and 'out' would hide layout/, about/,
-- router/, etc. Anchor directory names as path segments instead: '/war/' (nested)
-- and '^war/' (repo root). The dead '**/x/**' globs are left as intent documentation.
local wildignore_patterns = {
  '**/.Images/**',
  '%.Images',
  '**/.coc/**',
  '%.coc',
  '**/%.git/**',
  '%.git',
  '**/.idea/**',
  '%.idea',
  '**/.node_modules/**',
  '%.node_modules',
  '**/.packer%.nvim/**',
  '%.packer%.nvim',
  '**/.packer_compiled/**',
  '%.packer_compiled',
  '**/.yarn/**',
  '%.yarn',
  '**/deb/**',
  '/deb/',
  '^deb/',
  '**/dist/**',
  '/dist/',
  '^dist/',
  '**/event-collector/**',
  'event-collector',
  '**/event-transformer/**',
  'event-transformer',
  '**/kafka/**',
  'kafka',
  '**/navi-design-system/**',
  'navi-design-system',
  '**/node_modules/**',
  'node_modules',
  '**/out/**',
  '/out/',
  '^out/',
  '**/temp_deploy/**',
  'temp_deploy',
  '**/war/**',
  '/war/',
  '^war/',
  '*.class',
  '**/.yarn.lock',
  '**/yarn.lock',
  '.yarn.lock',
  'yarn.lock',
  '**/package-lock.json',
  'package-lock.json',
  '**/build/**',
  '/build/',
  '^build/',
  '**/coverage/**',
  '/coverage/',
  '^coverage/',
  '**/logs/**',
  '/logs/',
  '^logs/',
  '**/tmp/**',
  'tmp',
  '**/.cache/**',
  '.cache',
  '**/.vscode/**',
  '.vscode',
  '**/.DS_Store',
  '.DS_Store',
  '**/Thumbs.db',
  'Thumbs.db',
  '**/desktop.ini',
  'desktop.ini',
  '**/*.swp',
  '**/*.swo',
  '**/*.bak',
  '**/*.tmp',
}

return wildignore_patterns
